### ISSUE TITLE
CDI compatibility with Spring DI

### ISSUE THREAD

**Issue by prangdal** [jakartaee/jakartaee-platform#557]
**Is your feature request related to a problem? Please describe.**
Our enterprise application is getting upgraded to JSF2.3, Jakarta ee 10, running on tomcat 10 with jboss weld (CDI 4.0). We have extensive use of spring jdbcTemplate for persistence, we are not in a position to replace it immediately. Please suggest an alternative to bridge the gap here? or any suitable simplified persistence framework we can consider ? JPA is not an immediate option, considering the size and complexity .. 

**Describe the solution you'd like**
Any utility, extension to integrate spring with CDI 4.0 under jakarta 10, will help? any examples would help..

**Describe alternatives you've considered**
In search of alternatives ...

**Additional context**

**Comment by hantsy** [comment]
Spring implements the original JSR330(`@Inject`), not sure the future of Inject spec(being merged to CDI or still standalone), there is no update for years.

**Comment by hantsy** [comment]
Not sure how you are using the mixed stack, as I know Spring Data JPA is compatible with the old CDI 1.x(it does not support `annotated` type scan). 

If Spring Data JPA is in a JavaEE/JakartaEE container, you can use `Repository` freely as CDI beans.

And Spring can reuse all container resource, such as JTA transaction manager, EntityManagerFactory, DataSource, calling EJB by JNDI etc.

https://github.com/hantsy/spring-puzzles/tree/master/jakartaee-container-managed
