### ISSUE TITLE
Core Profile contains API of CDI full since there is no CDI lite artifact

### ISSUE THREAD

**Issue by rdebusscher** [jakartaee/jakartaee-platform#585]
The CDI API artefact contains all CDI classes, CDI Lite and CDI Full.  This means that an application compiled against the Core profile API might fail on a certified Core Profile runtime as the CDI Full classes are optional (and thus doesn't need to be supported)

See also https://github.com/jakartaee/cdi/issues/640

**Comment by ivargrimstad** [comment]
This seems to be addressed by https://github.com/jakartaee/cdi/issues/646. 

Is it ok to close this issue?
