### ISSUE TITLE
CompatibilityRequirements page is out of date

### ISSUE THREAD

**Issue by starksm64** [jakartaee/jakartaee-platform#605]
**Describe the bug**
https://eclipse-ee4j.github.io/jakartaee-platform/CompatibilityRequirements refers to a Java EE style of compatibility that is no longer applicable. We have switched to using a semantic versioning model, but this really is not captured anywhere.

**Comment by starksm64** [comment]
So this page is essentially the contents from the Java EE days with updates to replace expert groups with spec projects and Java EE with Jakarta EE. The specification committee needs to formalize what the compatibility requirements for Jakarta EE are and make that part of the JESP. This CompatibilityRequirements page can then add the additional context questions for clarification/context purposes.

**Comment by arjantijms** [comment]
Worked on via the spec committee
