### ISSUE TITLE
CN4J Jakarta EE & MicroProfile Releation Slide Deck

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [jakartaee/jakartaee-platform#607]
Hi, as presented today (2023-01-31) in the Jakarta EE Platform and MicroProfile Technical calls here is the slide deck to discuss the content futher offline.

Feel free to comment or ask for missing parts.
I only add the PDF here yet, if you want to have a different format, I can upload that on request (Keynote is the original, PowerPoint may be possible too).

After a general introduction the following issues an potential solutions can be found in the 2nd part:

- Continuous Integration
- MicroProfile Parent
- MicroProfile Metrics
- Jakarta EE Platform
- Jakarta Security & MicroProfile JWT
- Jakarta Config & MicroProfile Config
- Security Issues

[CN4J JEE MP Relation 20230131 01.pdf](https://github.com/eclipse-ee4j/jakartaee-platform/files/10550543/CN4J.JEE.MP.Relation.20230131.01.pdf)

**Comment by JanWesterkamp-iJUG** [comment]
Note: The current MP release planing contains a potential MP 7.0 release in 2023 - so the future MP release in the slide solutions might be a MP 8.0 - I will update the slides, when this will be more concrete.

**Comment by m-reza-rahman** [comment]
The Jakarta EE Ambassadors put a lot of thought into this a long time ago: https://docs.google.com/presentation/d/1zei-cHG9xSasb0NwLI03OO0zboCHBekDP0M6A8shLuo/edit?usp=sharing. I think most of it is still very relevant. Feel free to pull what adds value?

**Comment by JanWesterkamp-iJUG** [comment]
> The Jakarta EE Ambassadors put a lot of thought into this a long time ago: https://docs.google.com/presentation/d/1zei-cHG9xSasb0NwLI03OO0zboCHBekDP0M6A8shLuo/edit?usp=sharing. I think most of it is still very relevant. Feel free to pull what adds value?

Hi @m-reza-rahman, thanks for remind me to these slides.
I think most of this is already added to this slide deck here (https://docs.google.com/presentation/d/1wVaGJssQKPDSRcgRSE52mmm2Lb55THyUc_dGj7F5SAg/edit#slide=id.gbcfab764b6_0_221), but this needs to be updated too.

I tried to focus on the technical aspects for now, but for the organizational ones your Jakarta EE Ambassador slides would be very helpful and I will review my slides regarding the technical aspects.

**Comment by JanWesterkamp-iJUG** [comment]
Updated version of the slides:

- Organisations
- Component Specs
- Umbrella Specs (Profiles/Platform)
- Spec Implementations
- System Environment
- Jakarta EE & MicroProfile
- CN4J Roadmap
- Issues & Solutions
  - Continuous Integration
  - MicroProfile Parent
  - MicroProfile Spec
  - Jakarta EE Parent
  - Jakarta EE Spec
  - Jakarta EE Platform
  - MicroProfile Metrics
  - Jakarta Security & MP JWT
  - MP Config & Jakarta Config
  - MP Telemetry & OpenTelemetry
  - MP Metrics & MP Telemetry
  - MicroProfile REST Client

[CN4J JEE MP Relation 20230228 01.pdf](https://github.com/eclipse-ee4j/jakartaee-platform/files/10851349/CN4J.JEE.MP.Relation.20230228.01.pdf)

**Comment by JanWesterkamp-iJUG** [comment]
Updated version with minor fixes/updates in headlines:
[CN4J JEE MP Relation 20230306 01.pdf](https://github.com/eclipse-ee4j/jakartaee-platform/files/10899520/CN4J.JEE.MP.Relation.20230306.01.pdf)

**Comment by JanWesterkamp-iJUG** [comment]
@arjantijms what's the reason to close this?

I planed updates from time to time on this and not all of the already documented issues/solutions are solved yet.
