### ISSUE TITLE
 searching inside java doc for jakarata ee 10 return 404

### ISSUE THREAD

**Issue by Just-some-one** [jakartaee/jakartaee-platform#676]
the returned link from the search add extra path to the correct link

1. Go [jakarta ee 10 javadoc](https://jakarta.ee/specifications/platform/10/apidocs/)
2. use the search for any class/method (but not package)
3. click on the returned link 
4. will return the `404 Page Not Found `

cause of the issue that the returned link add extra path to correct link`undefined`

for example searching for `jaxbcontext` then click on the link it return 
https://jakarta.ee/specifications/platform/10/apidocs/undefined/jakarta/xml/bind/JAXBContext.html
while it should return 
https://jakarta.ee/specifications/platform/10/apidocs/jakarta/xml/bind/JAXBContext.html

thanks for your help and have a nice day :)

[AB#50](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/50)

**Comment by ivargrimstad** [comment]
Let's see if we can fix this in the build for EE11 and then release a patch of the EE10 javadocs with the fix afterwards

**Comment by Just-some-one** [comment]
thanks @ivargrimstad

**Comment by lukasj** [comment]
https://github.com/jakartaee/jakartaee-api/pull/140 can fix this

**Comment by Just-some-one** [comment]
thanks @lukasj
