### ISSUE TITLE
Wave discussion: Refresh JakartaEE11ReleasePlan.md with a view toward getting it beyond DRAFT

### ISSUE THREAD

**Issue by edburns** [jakartaee/jakartaee-platform#681]
Consider https://github.com/jakartaee/jakartaee-platform/blob/gh-pages/jakartaee11/JakartaEE11ReleasePlan.md

The **Waves** section needs to be refreshed to keep in mind the following concerns.

1. Pragmatic: getting it done
2. Latest dependency analysis @janwesterkamp-ijug
3. Lowest priority, not universally accepted as necessary, but worth exploring: ability to combine related specs into one:
   - XML web services specs
   - JSON specs
   - Security specs
   - CDI related specs

**Comment by JanWesterkamp-iJUG** [comment]
The (current) result for API dependencies (only):

Wave 1:

- Jakarta Activation
- Jakarta Annotation*
- Jakarta Authentication
- Jakarta EJB
- Jakarta EL
- Jakarta Lang Model
- Jakarta Inject
- Jakarta JSON
- Jakarta Persistence
- Jakarta Security
- Jakarta Servlet
- Jakarta Validation
- Jakarta REST
- Jakarta Websocket Client

Wave 2:

- Jakarta Authorization
- Jakarta Interceptor*
- Jakarta JMS
- Jakarta JSON Bind
- Jakarta Mail
- Jakarta Servlet JSP
- Jakarta Websocket
- Jakarta XMP Bind
- Jakarta XML SOAP

Wave 3:

- Jakarta CDI*
- Jakarta Servlet JSP JSTL
- Jakarta XML WS

Wave 4:

- Jakarta Batch
- Jakarta Concurrent
- Jakarta Transaction*
- Jakarta Platform Web Profile

Wave 5:

- Jakarta Faces*
- Jakarta Ressource

Wave 6:

- Jakarta Platform Web Profile*

Wave 7:

- Jakarta Platform*

* critical path

@edburns and @arjantijms: I hope this first review of the waves is helpful?

**Comment by edburns** [comment]
THanks, @JanWesterkamp-iJUG , this is a great way to keep the progress going. We'll continue this in #685 .

**Comment by JanWesterkamp-iJUG** [comment]
@edburns, a little follow up:

To fix the issues in the newest jQA version 2.0 I created these issues:

- https://github.com/jqassistant-demo/jakarta-ee-dependencies/issues/9
- https://github.com/jqassistant-demo/jakarta-ee-dependencies/issues/10
- https://github.com/jqassistant-demo/jakarta-ee-dependencies/issues/8

But version 1.2 can still be used meanwhile.

**Comment by DirkMahler** [comment]
> @edburns, a little follow up:
> 
> To fix the issues in the newest jQA version 2.0 I created these issues:
> 
>     * [jQA 2.0 does not run with Java SE 17 jqassistant-demo/jakarta-ee-dependencies#9](https://github.com/jqassistant-demo/jakarta-ee-dependencies/issues/9)
> 
>     * [GraphML report plugin is missing jqassistant-demo/jakarta-ee-dependencies#10](https://github.com/jqassistant-demo/jakarta-ee-dependencies/issues/10)
> 
>     * [The ELK rendering creates an issue that prevents diagram rendering jqassistant-demo/jakarta-ee-dependencies#8](https://github.com/jqassistant-demo/jakarta-ee-dependencies/issues/8)
> 
> 
> But version 1.2 can still be used meanwhile.

The issues with jQA 2.0 should be fixed now, sorry for the inconvenience.
